import React, { useRef } from 'react';
import { Link } from 'gatsby';
import LayoutInfo from '../components/layout/layout-info';
import Card from '../components/common/card';
import { Button } from 'semantic-ui-react';
import { parent, hero, sectionContent, cardGallery } from './landing_page.module.css';

export default function Home() {
    const yearRef = useRef(new Date().getFullYear());


    return (
        <LayoutInfo header={""}>
            <div className={parent}>
                <div className={hero}>
                    <div className={sectionContent}>
                        <h1>SWAMP Data Dashboard</h1>
                        <p>The Surface Water Ambient Monitoring Program (SWAMP) mission is to generate  high quality, accessible, and usable data and information that is used to protect and restore California’s watersheds, and to inform California communities about local conditions of waterbodies monitored by SWAMP. This dashboard provides data generated by SWAMP for the time period of 2000-{yearRef.current}.</p>
                        <Link to="/explore_data"><Button size="medium" color="blue">Explore the data</Button></Link>
                    </div>
                </div>
                <div className="section">
                    <div className={cardGallery}>
                        <Card imagePath={`card_image_dashboard.jpg`} imageAlt={'Digital map of monitoring sites'} link={'/explore_data'}>
                            <h2>
                                Dashboard
                            </h2>
                            <p>Explore SWAMP water quality data, trends, and more on an interactive platform.</p>
                        </Card>
                        <Card imagePath={`card_image_learn.jpg`} imageAlt={'Scientists wading in a stream'} link={'/learn'}>
                            <h2>
                                Learn
                            </h2>
                            <p>Read about how SWAMP measures water quality and calculates trends.</p>
                        </Card>
                        <Card imagePath={`card_image_data.jpg`} imageAlt={'Aerial photograph of a river and a city in the background'}>
                            <h2>
                                Data
                            </h2>
                            <p>Access and download SWAMP data from the dashboard and other platforms.</p>
                        </Card>
                    </div>
                </div>
            </div>
        </LayoutInfo>
    )
}

