import React from 'react';
import SearchContainer from '../search/search-container';
import AnalyteMenu from '../map-controls/analyte-menu';
import RegionMenu from '../map-controls/region-menu';

export default function Home({ selectedAnalyte, selectedRegion, setAnalyte, setRegion, setView }) {
    return (
        <React.Fragment>
            <p>The Surface Water Ambient Monitoring Program (SWAMP) mission is to generate  high quality, accessible, and usable data and information that is used to protect and restore California’s watersheds, and to inform California communities about local conditions of waterbodies monitored by SWAMP. To learn more about SWAMP and the work we do, check out our <a href="https://www.waterboards.ca.gov/water_issues/programs/swamp/" target="_blank" rel="noopener noreferrer">website</a>!</p>
            <p>This dashboard provides data generated by SWAMP for the time period of 2000-2021. Select a monitoring site from the map or explore the data by water quality parameter or region.</p>
            <h2>Explore SWAMP data</h2>
            <AnalyteMenu selectedAnalyte={selectedAnalyte} setAnalyte={setAnalyte} />
            <RegionMenu selectedRegion={selectedRegion} setRegion={setRegion} setView={setView} />
            <h2>Search SWAMP data</h2>
            <SearchContainer />
        </React.Fragment>
    )
}