import React, { useRef } from 'react';
import Layout from '../components/layout/layout';
import Card from '../components/common/card';
import { Button } from 'semantic-ui-react';
import { parent, hero, sectionContent, cardGallery, footer, copyright, logoContainer, logo } from './home.module.css';

export default function Home() {
    const yearRef = useRef(new Date().getFullYear());


    return (
        <Layout>
            <div className={parent}>
                <div className={hero}>
                    <div className={sectionContent}>
                        <h1>SWAMP Data Dashboard</h1>
                        <p>The Surface Water Ambient Monitoring Program (SWAMP) mission is to generate  high quality, accessible, and usable data and information that is used to protect and restore California’s watersheds, and to inform California communities about local conditions of waterbodies monitored by SWAMP. This dashboard provides data generated by SWAMP for the time period of 2000-{yearRef.current}.</p>
                        <Button size="medium" color="teal">Explore the data</Button>
                    </div>
                </div>
                <div className="section">
                    <div className={cardGallery}>
                        <Card imagePath={`card_image_dashboard.jpg`} imageAlt={'Map of monitoring sites near Grass Valley, California'}>
                            <h2>
                                Dashboard
                            </h2>
                            <p>Explore SWAMP water quality data, trends, and more on an interactive platform.</p>
                        </Card>
                        <Card imagePath={`card_image_learn.jpg`} imageAlt={'Scientists wading in a stream'}>
                            <h2>
                                Learn
                            </h2>
                            <p>Learn about common water quality indicators and how to interpret SWAMP data.</p>
                        </Card>
                        <Card imagePath={`card_image_data.jpg`} imageAlt={'Map showing SWAMP monitoring sites'}>
                            <h2>
                                Data
                            </h2>
                            <p>Access and download SWAMP data from the dashboard and other platforms.</p>
                        </Card>
                    </div>
                </div>
                <div className={footer}>
                    <div className={sectionContent}>
                        <div className={logoContainer}>
                            <img className={logo} src={`swamp_logo_black_small.png`} alt='SWAMP logo' />
                            <img className={logo} src={`wb_logo_black_small.png`} alt='Water Boards logo' />
                        </div>
                        <span className={copyright}>
                            Copyright © {yearRef.current} State of California<br />
                            Surface Water Ambient Monitoring Program&nbsp;&nbsp;|&nbsp;&nbsp;California Water Boards
                        </span>
                    </div>
                </div>
            </div>
        </Layout>
    )
}

