import React, { useState } from 'react';
import Layout from '../components/layout/layout';
import MapIndex from '../components/map/map-index';
import AnalyteMenu from '../components/map-controls/analyte-menu';
import RegionMenu from '../components/map-controls/region-menu';
import TableIndex from '../components/table-index/table-index';
import { mapContainer, mainContainer, infoContainer, twinContainer, twin } from './index.module.css';

export default function Index() {
  const [analyte, setAnalyte] = useState(null);
  const [region, setRegion] = useState(null);
  const [site, setSite] = useState(null);


  return (
    <Layout>
      <div className={mapContainer}>
        <MapIndex selectedAnalyte={analyte} selectedRegion={region} clickedSite={site} />
      </div>
      <div className={mainContainer}>
        <div className={infoContainer}>
          <p>The Surface Water Ambient Monitoring Program (SWAMP) mission is to generate  high quality, accessible, and usable data and information that is used to protect and restore California’s watersheds, and to inform California communities about local conditions of waterbodies monitored by SWAMP. To learn more about SWAMP and the work we do, check out our <a href="https://www.waterboards.ca.gov/water_issues/programs/swamp/" target="_blank" rel="noopener noreferrer">website</a>!</p>
          <p>This dashboard provides data generated by SWAMP for the time period of 2000-2021. Select a monitoring site from the map or explore the data by water quality parameter or region.</p>
          <h2>Explore SWAMP data</h2>
          {/* Controls */}
          <div className={twinContainer}>
            <div className={twin} style={{ marginRight: '12px' }}>
              <RegionMenu selectedRegion={region} setRegion={setRegion} />
            </div>
            <div className={twin}>
              <AnalyteMenu selectedAnalyte={analyte} setAnalyte={setAnalyte} />
            </div>
          </div>
          {/* Table */}
          <div style={{ marginTop: '12px' }}>
            <TableIndex selectedAnalyte={analyte} selectedRegion={region} setSite={setSite} />
          </div>
        </div>
      </div>
    </Layout>
  )
}
