import React, { useState } from 'react';
import Layout from '../components/layout/layout';
import MapIndex from '../components/map/map-index';
import ControlsContainer from '../components/map-controls/controls-container';
import ChartIndex from '../components/chart-index/chart-index';
import TableIndex from '../components/table-index/table-index';
import { mapContainer, mainContainer, infoContainer } from './index.module.css';

export default function Index() {
  const [analyte, setAnalyte] = useState(null);
  const [region, setRegion] = useState(null);
  const [site, setSite] = useState(null);
  const [selectedSites, setSelectedSites] = useState([]);


  return (
    <Layout>
      <div className={mapContainer}>
        <MapIndex 
          selectedAnalyte={analyte} 
          selectedRegion={region} 
          setSelectedSites={setSelectedSites}
          clickedSite={site} 
        />
      </div>
      <div className={mainContainer}>
        <div className={infoContainer}>
          <p>The Surface Water Ambient Monitoring Program (SWAMP) mission is to generate  high quality, accessible, and usable data and information that is used to protect and restore California’s watersheds, and to inform California communities about local conditions of waterbodies monitored by SWAMP. To learn more about SWAMP and the work we do, check out our <a href="https://www.waterboards.ca.gov/water_issues/programs/swamp/" target="_blank" rel="noopener noreferrer">website</a>!</p>
          <p>This dashboard provides data generated by SWAMP for the time period of 2000-2021. Select a monitoring site from the map or explore the data by water quality parameter or region.</p>
          <h2>Explore SWAMP data</h2>
          {/* Controls */}
          <div>
            <div id="searchContainer" style={{ border: '1px solid #6e6e6e', marginBottom: '1em' }} />
            <ControlsContainer 
              selectedRegion={region}
              setRegion={setRegion}
              selectedAnalyte={analyte}
              setAnalyte={setAnalyte}
            />
            <ChartIndex 
              selectedSites={selectedSites}
              analyte={analyte}
            />
            {/*
            <TableIndex 
              selectedRegion={region} 
              setRegion={setRegion} 
              selectedAnalyte={analyte}
              setAnalyte={setAnalyte}
              setSite={setSite} />
            */}
          </div>
        </div>
        <div id="indexTableContainer" style={{ padding: '0 20px', marginBottom: '100px' }}></div>
      </div>
    </Layout>
  )
}
